language: node_js
node_js:
  - node
  - 8
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - mongo books-test --eval 'db.createUser({user:"sarra",pwd:"sarra",roles:["readWrite"]});'
  - mongo books-test --eval 'db.createCollection("books");'
  - sleep 15
test: npm test
