version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:3000"
    links:
      -  mongo
    environment:
      - ROOT_URL = http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/books-test
  mongo:
    image: mongo
    ports:
       - "27017:27017"
